### PR TITLE
Quick fix for dicom output failure #1128

### LINKED ISSUE #1128: MR  Dicom writer fails
The following error crashes the gadgetron server when trying to write an MR reconstruction to DICOM with the script below:
```
... some Gadgetron stream output...

07-28 14:18:04.857 INFO [GadgetStreamController.cpp:313]   Gadget class: DicomFinishGadget
07-28 14:18:04.857 INFO [GadgetStreamController.cpp:328]   Gadget parameters: 0
07-28 14:18:04.857 INFO [GadgetStreamController.cpp:356] Gadget Stream configured
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unable to load ISMRMRD Meta XML document
Aborted (core dumped)
```
The script succeeds at writing dicom files for idx_file_to_run = 0,1 (where also the attribute XML file is generated) and fails for idx_file_to_run = 2,3
```
import sirf.Gadgetron as pMR
import numpy as np 
import os

def normalise_image_data(img):

    img = img.abs()

    img_max = np.max(img.as_array())
    img_min = np.min(img.as_array())

    img = 2**16 * (img - img_min)/(img_max-img_min)

    return img

sirf_install_path = str(os.getenv("SIRF_INSTALL_PATH"))
fpath_in = sirf_install_path + "/share/SIRF-3.3/data/examples/MR/" 

fnames_in = ["simulated_MR_2D_cartesian.h5",
"grappa2_1rep.h5",
"simulated_MR_2D_cartesian_Grappa2.h5",
"grappa2_6rep.h5"]

fname_out = "/media/sf_CCPPETMR/tmp_recon.dcm" # or whatever path you have write access to

idx_file_to_run = 0 # or 1, 2, 3
ad = pMR.AcquisitionData(fpath_in + fnames_in[idx_file_to_run])
ad = pMR.preprocess_acquisition_data(ad)
ad.sort()

recon = pMR.CartesianGRAPPAReconstructor()
recon.set_input(ad)

recon.process()
id = recon.get_output()
id = normalise_image_data(id)

id.write(fname_out)
```

I am on a VM at `origin/master` and build against `ISMRMRD/v1.7.0` and Gadgetron is also built against this ISMRMRD version at the commit `b6191eaaa72ccca6c6a5fe4c0fa3319694f512ab`.

### PR DESCRIPTION
**Pull request by evgueni-ovtchinnikov**
## Changes in this pull request
Enabled dicom output for MR reconstruction with Gadgetron.

## Testing performed
Tested on examples.

## Related issues

Quick fixes #1128.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have added docstrings/doxygen in line with the guidance in the developer guide
- [ ] I have implemented unit tests that cover any new or modified functionality
- [x] The code builds and runs on my machine
- [ ] CHANGES.md has been updated with any functionality change

## Contribution Notes

Please read and adhere to the [contribution guidelines](https://github.com/SyneRBI/SIRF/blob/master/CONTRIBUTING.md).

Please tick the following: 

 - [x] The content of this Pull Request (the Contribution) is intentionally submitted for inclusion in SIRF (the Work) under the terms and conditions of the [Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0) License.

### CODE REVIEW

File: src/xGadgetron/cGadgetron/gadgetron_x.cpp [hunk 1]
```diff
@@ -288,6 +296,7 @@ ImagesProcessor::process(const GadgetronImageData& images)
 		THROW("DICOM writer does not support complex images");
 
 	std::string config = xml();
+	std::cout << xml() << '\n';
```
Comment (KrisThielemans) [inline src/xGadgetron/cGadgetron/gadgetron_x.cpp:299]: i guess this has to be removed

File: src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadget_lib.h [hunk 2]
```diff
@@ -356,7 +356,29 @@ namespace sirf {
...
+		FFTGadget() :
+			Gadget("FFT", "gadgetron_mricore", "FFTGadget")
+		{}
+		static const char* class_name()
+		{
+			return "FFTGadget";
+		}
+	};
+
+	class CombineGadget : public Gadget {
```
Comment (KrisThielemans) [inline src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadget_lib.h:370]: add some doxygen what this is supposed to do

File: src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadget_lib.h [hunk 3]
```diff
@@ -356,7 +356,29 @@ namespace sirf {
 		}
 	};
 
-    class GenericReconCartesianFFTGadget : public Gadget {
+	class FFTGadget : public Gadget {
```
Comment (KrisThielemans) [inline src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadget_lib.h:359]: add some doxygen what this is supposed to do

File: src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadgetron_x.h [hunk 4]
```diff
@@ -253,7 +253,7 @@ namespace sirf {
 			return "ImagesReconstructor";
 		}
 
-		void process(MRAcquisitionData& acquisitions);
+		void process(MRAcquisitionData& acquisitions, const char* dcm_prefix = "image");
```
Comment (KrisThielemans) [inline src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadgetron_x.h:256]: I'd prefer to have a `set_dcm_prefix` or similar function. Adding it as an optional argument is rather non-standard.

File: src/xGadgetron/pGadgetron/Gadgetron.py [hunk 5]
```diff
@@ -1435,14 +1435,21 @@ def set_input(self, input_data):
         '''
         assert isinstance(input_data, AcquisitionData)
         self.input_data = input_data
-    def process(self):
+    def process(self, dcm_prefix=None):
```
Comment (KrisThielemans) [inline src/xGadgetron/pGadgetron/Gadgetron.py:1438]: I'd prefer to have a `set_dcm_prefix` or similar function. Adding it as an optional argument is rather non-standard.

File: src/xGadgetron/pGadgetron/Gadgetron.py [hunk 6]
```diff
@@ -1435,14 +1435,21 @@ def set_input(self, input_data):
...
         '''
         Processes the input with the gadget chain.
+        dcm_prefix: Python text string.
+        If dcm_prefix is not None, the reconstructed images are written to
+        files <dcm_prefix>_<image number>.dcm.
+        Otherwise, they are stored in memory and can be retrieved by
```
Comment (KrisThielemans) [inline src/xGadgetron/pGadgetron/Gadgetron.py:1444]: Is it really "otherwise", i.e. will `get_output()` not work? that'd be a pity.

**Review by KrisThielemans — CHANGES_REQUESTED** [review]
best to add a test case for it (if easy)

**Comment by KrisThielemans** [comment]
failures:
- https://github.com/SyneRBI/SIRF/actions/runs/3300780314/jobs/5445623930#step:8:999 `cGT_reconstructImages() missing 1 required positional argument: 'dcm_prefix'`
- https://github.com/SyneRBI/SIRF/actions/runs/3300780314/jobs/5445623930#step:8:1080
  `Expected output of reconstruction to be complex`

File: src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadgetron_x.h (hunk 4 above)
Comment (evgueni-ovtchinnikov) [reply src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadgetron_x.h]: done

File: src/xGadgetron/cGadgetron/gadgetron_x.cpp (hunk 1 above)
Comment (evgueni-ovtchinnikov) [reply src/xGadgetron/cGadgetron/gadgetron_x.cpp]: sure

File: src/xGadgetron/pGadgetron/Gadgetron.py (hunk 6 above)
Comment (evgueni-ovtchinnikov) [reply src/xGadgetron/pGadgetron/Gadgetron.py:1447]: Yes, unfortunately the set of gadgets in currently used Gadgetron 3.17 does not seem to allow sending images to both the Gadgetron client and DICOM files. I might try to edit `DicomFinishGadget` so that it sends ISMRMRD images to the client but, assuming I succeed, do we want to ship our modification of Gadgetron with SIRF?
To remind you, this PR is just a quick fix, for a proper one we need help from Gadgetron people, but we can only get it once we moved to the recent Gadgetron.

File: src/xGadgetron/pGadgetron/Gadgetron.py (hunk 5 above)
Comment (evgueni-ovtchinnikov) [reply src/xGadgetron/pGadgetron/Gadgetron.py]: done

File: src/xGadgetron/pGadgetron/Gadgetron.py (hunk 6 above)
Comment (KrisThielemans) [reply src/xGadgetron/pGadgetron/Gadgetron.py:1447]: ok. as long as it's clear in the documentation. Maybe let `get_output()` check if the prefix was set, and if so raise a runtime error that's somewhat informative.

File: src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadget_lib.h (hunk 2 above)
Comment (evgueni-ovtchinnikov) [reply src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadget_lib.h:405]: done

File: src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadget_lib.h (hunk 3 above)
Comment (evgueni-ovtchinnikov) [reply src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadget_lib.h:391]: done

File: src/xGadgetron/pGadgetron/Gadgetron.py (hunk 6 above)
Comment (evgueni-ovtchinnikov) [reply src/xGadgetron/pGadgetron/Gadgetron.py:1447]: done

File: src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadgetron_x.h [hunk 7]
```diff
@@ -253,15 +253,31 @@ namespace sirf {
...
+		{
+			dcm_prefix_ = dcm_prefix;
+		}
+		std::string dcm_prefix() const
+		{
+			return dcm_prefix_;
+		}
+		bool dcm_output() const
+		{
+			return dcm_prefix_.size() > 1;
```
Comment (KrisThielemans) [inline src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadgetron_x.h:266]: probably should be `>0` I guess, but better to check `!dcm_prefix.empty()`

File: src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadgetron_x.h [hunk 8]
```diff
@@ -253,15 +253,31 @@ namespace sirf {
 			return "ImagesReconstructor";
 		}
 
+		void set_dcm_prefix(const char* dcm_prefix)
+		{
+			dcm_prefix_ = dcm_prefix;
```
Comment (KrisThielemans) [inline src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadgetron_x.h:258]: - add a check `dcm_prefix` is not null. Although why do you want a `const char*`. I'd vastly prefer a `const std::string&` (it'll auto-convert anyway)
- add a doxygen string that it needs to be set to an empty string to disable DICOM output.

File: src/xGadgetron/pGadgetron/Gadgetron.py [hunk 9]
```diff
@@ -1435,14 +1436,21 @@ def set_input(self, input_data):
         '''
         assert isinstance(input_data, AcquisitionData)
         self.input_data = input_data
+    def set_dcm_prefix(self, dcm_prefix):
+        self.dcm_prefix = dcm_prefix
     def process(self):
         '''
         Processes the input with the gadget chain.
+        dcm_prefix: Python text string.
+        If dcm_prefix is not None, the reconstructed images are written to
```
Comment (KrisThielemans) [inline src/xGadgetron/pGadgetron/Gadgetron.py:1445]: actually at the moment you set it "", not to `None`. are both handled the same?

**Review by KrisThielemans — CHANGES_REQUESTED** [review]

File: src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadgetron_x.h (hunk 7 above)
Comment (evgueni-ovtchinnikov) [reply src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadgetron_x.h]: done

File: src/xGadgetron/pGadgetron/Gadgetron.py (hunk 9 above)
Comment (evgueni-ovtchinnikov) [reply src/xGadgetron/pGadgetron/Gadgetron.py]: just forgot to change None (used in my first design) to "", corrected now

**Review by KrisThielemans — APPROVED** [review]
great. Feel free to merge whenever you're ready (after adding something to `CHANGES.md`)
