### PR TITLE
A proper fix of issue 914.

### LINKED ISSUE #915: Proper solution to #914
#914 can be urgently quick fixed in Python for now. However, proper not urgent solution is to provide access to existing C++ image and acquisition templates in Python so that they will become automatically available in the linear part of the acquisition model.

### PR DESCRIPTION
**Pull request by evgueni-ovtchinnikov**
Provides access to the range and domain geometry data of C++ `AcquisitionModel` classes, fixes #915.

### CODE REVIEW

File: src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadgetron_x.h [hunk 1]
```diff
@@ -417,6 +417,16 @@ namespace sirf {
 			check_data_role(*sptr_ic);
 			sptr_imgs_ = sptr_ic;
 		}
+		// Returns shared pointer to the acquisitions template used.
```
Comment (KrisThielemans) [inline src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadgetron_x.h:420]:
```suggestion
		//! Returns shared pointer to the acquisitions template used. 
```
this way it'll end up in doxygen

File: src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadgetron_x.h [hunk 2]
```diff
@@ -417,6 +417,16 @@ namespace sirf {
 			check_data_role(*sptr_ic);
 			sptr_imgs_ = sptr_ic;
 		}
+		// Returns shared pointer to the acquisitions template used. 
+		gadgetron::shared_ptr<const MRAcquisitionData> acq_template_sptr() const
+		{
+			return sptr_acqs_;
+		}
+		// Returns shared pointer to the images template used.
```
Comment (KrisThielemans) [inline src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadgetron_x.h:425]:
```suggestion
		//! Returns shared pointer to the images template used. 
```

**Review by KrisThielemans — CHANGES_REQUESTED** [review]
Looks good to me (but of course didn't check in detail!).

Can you fix the [Codacy issue](https://app.codacy.com/gh/SyneRBI/SIRF/pullRequest?prid=7547140) (trailing white-space), but more importantly update `CHANGES.md` and possibly even the UserGuide. Then merge!

thanks a lot
